### ISSUE TITLE
Cannot make it work on O3DS on 11.17

### ISSUE THREAD

**Issue by AliquodFahriam** [PabloMK7/3dsropxploitinjector#1]
I've seen that, with this new release, you added 11.17 support. However the game crashes when I try to rename the team. 
Any suggestion?

**Comment by PabloMK7** [comment]
I don't know what you mean. What team?

**Comment by AliquodFahriam** [comment]
I am following the guide at this link: https://wiki.hacks.guide/wiki/3DS:Alternate_Exploits/3dsropxploitinjector_(basehaxx). 
It says to inject the payload throug a 3ds with custom firmware and then open the game in the target 3ds (which I suppose is the one without custom firmware). I am referring to this section in particular:
Section III - Launching the payload

1.  Launch your copy of Omega Ruby/Alpha Sapphire on the target 3DS
2. Enter your secret base
3. The name on the flag will be replaced with a lot of '?'
4. Boot the PC up, select Edit secret team settings, then Change team name
5. You will load into the basehaxx in-game menu
6. Press (A) to launch the *hax payload
7. This may take a few tries
8. If the exploit was successful, your target 3DS will load into the 3DS ROP xPloit Injector

At step number 5 the game crashes and, instead of dhe basehaxx menu the console reboots and I have to start all over. 
Yesterday I checked the nintendo homebrew discord and I saw someone having the same problem.

**Comment by PabloMK7** [comment]
Make sure you have the latest release of [3DSROPxPloitInjector](https://github.com/PabloMK7/3dsropxploitinjector/releases/latest) (it was updated 12 hours ago). If that doesn't fix it, then the problem is in basehax and not 3DSROPxPloitInjector. 

In any case, I don't know how to help you other than that. This is a bug tracker meant to keep a list of bugs in the project, and not appropriate for giving support. You can instead try to ask in the Nintendo Homebrew discord server, I'm also there so I can send a message there if I come with any ideas.
